#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '2':
        pose: mecanum1/pose
        pose2d: mecanum1/ground_pose
        child_frame_id: Robot_1/base_link
        parent_frame_id: world
    '3':
        pose: mecanum2/pose
        pose2d: mecanum2/ground_pose
        child_frame_id: Robot_2/base_link
        parent_frame_id: world
    '1':
        pose: object/pose
        pose2d: object/ground_pose
        child_frame_id: Robot_3/base_link
        parent_frame_id: world

optitrack_config:
        multicast_address: 239.255.42.99
